### ISSUE TITLE
ground truth 3D model

### ISSUE THREAD

**Issue by HelliceSaouli** [openMVG/SfM_quality_evaluation#4]
Hello
is it possible to have the ground truth 3D model for Fountain and herz please

**Comment by pmoulon** [comment]
Sure just look there in the section "MVS - Point Cloud - Surface accuracy"
https://github.com/openMVG/awesome_3DReconstruction_list

The data are there: https://icwww.epfl.ch/~marquez/multiview/denseMVS.html

**Comment by HelliceSaouli** [comment]
I already checked there. the link to the model is dead

**Comment by pmoulon** [comment]
Since the data have been moved, just modify the link by hand:
https://icwww.epfl.ch/~marquez/data/multiview/fountain.ply.bz2

**Comment by HelliceSaouli** [comment]
modify what? it is always saying ( requested link was not found on this server.)

**Comment by pmoulon** [comment]
I mean the link to the fountain PLY is not working there: https://icwww.epfl.ch/~marquez/multiview/modelFountain.html
But if you change it from https://icwww.epfl.ch/data/multiview/fountain.ply.bz2 to https://icwww.epfl.ch/~marquez/data/multiview/fountain.ply.bz2 it is working!

**Comment by HelliceSaouli** [comment]
I'm really sorry to trouble you. but it is alwz not working .
and if go to : https://icwww.epfl.ch/~marquez/
i get : You don't have permission to access 
![notworking](https://user-images.githubusercontent.com/10406314/35765397-b8d62bca-08ba-11e8-954e-140124677d4f.png)

**Comment by pmoulon** [comment]
It should be due to epfl server trouble.

**Comment by HelliceSaouli** [comment]
Well can you upload the models in here if you have them that will be super nice

**Comment by HelliceSaouli** [comment]
I think i figured out the problem. I don't know but my browsers refused to start downloading the file and I had to copy the link directly to the download manager and I got the models. sorry to waste your time lol x')

**Comment by HelliceSaouli** [comment]
here is the correct link : https://icwww.epfl.ch/~marquez/multiview/fountain.ply.bz2
the model is not in the data file XD man  they should fix this

**Comment by philleer** [comment]
Sorry to trouble you, but still don't know where to get the fountain.ply.bz2 ground truth since the links you give above do not work.

@HelliceSaouli do you mean point cloud [fountain-P11_Ground_Truth-Subsampled.ply](https://github.com/philleer/Dataset_For_3D_Reconstruction/blob/master/fountain-P11.ply.zip)
since I got this by chance but forget where I got it.

**Comment by philleer** [comment]
By the way, is there any decription of the point cloud? Such as the relation between the origin of the point cloud and the given camera poses, since it seems they are not consistent.

**Comment by philleer** [comment]
By the way, is there any decription of the point cloud? Such as the relation between the origin of the point cloud and the given camera poses, since it seems they are not consistent.
